'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class bookroom
    
    '''<summary>
    '''pax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pax As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''nights control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nights As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''Select1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Select1 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''Select2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Select2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''Select3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Select3 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''Select4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Select4 As Global.System.Web.UI.HtmlControls.HtmlSelect
End Class
