'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reservation
    
    '''<summary>
    '''RoomType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RoomDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomType1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RoomDescription1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomDescription1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomID1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomType2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RoomDescription2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomDescription2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomID2 As Global.System.Web.UI.WebControls.TextBox
End Class
