'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageReservation
    
    '''<summary>
    '''FullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FullName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CheckIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckIn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckOut As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Payment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Payment As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DepAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ReservationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReservationID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FullName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FullName1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomType1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CheckIn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckIn1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckOut1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckOut1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DepAmount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepAmount1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ReservationID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReservationID1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FullName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FullName2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomType2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CheckIn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckIn2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckOut2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckOut2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DepAmount2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepAmount2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ReservationID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReservationID2 As Global.System.Web.UI.WebControls.TextBox
End Class
